<?php

namespace ContainerVatGb0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OctoH5oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OctoH5o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OctoH5o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activite' => ['privates', '.errored..service_locator.OctoH5o.App\\Entity\\Activite', NULL, 'Cannot autowire service ".service_locator.OctoH5o": it references class "App\\Entity\\Activite" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'activite' => 'App\\Entity\\Activite',
            'entityManager' => '?',
        ]);
    }
}
