<?php

namespace ContainerVatGb0R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HP8AAXHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hP8AAXH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hP8AAXH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activiteRepository' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'markdown' => ['privates', 'cebe\\markdown\\Markdown', 'getMarkdownService', true],
        ], [
            'activiteRepository' => 'App\\Repository\\ActiviteRepository',
            'markdown' => 'cebe\\markdown\\Markdown',
        ]);
    }
}
