<?php

namespace ContainerXoqfwqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HRe3efhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HRe3efh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HRe3efh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ActiviteRepository', 'getActiviteRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.HRe3efh.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.HRe3efh": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'repo' => 'App\\Repository\\ActiviteRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
