<?php

namespace ContainerXoqfwqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O0HYL7ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o0HYL7Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o0HYL7Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActiviteController::activite_desinscription' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController::activite_inscription' => ['privates', '.service_locator.d7.fgxg', 'get_ServiceLocator_D7_FgxgService', true],
            'App\\Controller\\ActiviteController::delete' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController::edit' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController::index' => ['privates', '.service_locator.hP8AAXH', 'get_ServiceLocator_HP8AAXHService', true],
            'App\\Controller\\ActiviteController::mesactivites' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\ActiviteController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActiviteController::show' => ['privates', '.service_locator.DX5IRBd', 'get_ServiceLocator_DX5IRBdService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.HRe3efh', 'get_ServiceLocator_HRe3efhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ActiviteController:activite_desinscription' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController:activite_inscription' => ['privates', '.service_locator.d7.fgxg', 'get_ServiceLocator_D7_FgxgService', true],
            'App\\Controller\\ActiviteController:delete' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController:edit' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController:index' => ['privates', '.service_locator.hP8AAXH', 'get_ServiceLocator_HP8AAXHService', true],
            'App\\Controller\\ActiviteController:mesactivites' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\ActiviteController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActiviteController:show' => ['privates', '.service_locator.DX5IRBd', 'get_ServiceLocator_DX5IRBdService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.HRe3efh', 'get_ServiceLocator_HRe3efhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ActiviteController::activite_desinscription' => '?',
            'App\\Controller\\ActiviteController::activite_inscription' => '?',
            'App\\Controller\\ActiviteController::delete' => '?',
            'App\\Controller\\ActiviteController::edit' => '?',
            'App\\Controller\\ActiviteController::index' => '?',
            'App\\Controller\\ActiviteController::mesactivites' => '?',
            'App\\Controller\\ActiviteController::new' => '?',
            'App\\Controller\\ActiviteController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ActiviteController:activite_desinscription' => '?',
            'App\\Controller\\ActiviteController:activite_inscription' => '?',
            'App\\Controller\\ActiviteController:delete' => '?',
            'App\\Controller\\ActiviteController:edit' => '?',
            'App\\Controller\\ActiviteController:index' => '?',
            'App\\Controller\\ActiviteController:mesactivites' => '?',
            'App\\Controller\\ActiviteController:new' => '?',
            'App\\Controller\\ActiviteController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
