<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAzO7cQF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAzO7cQF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAzO7cQF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAzO7cQF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAzO7cQF\App_KernelDevDebugContainer([
    'container.build_hash' => 'AzO7cQF',
    'container.build_id' => '8b171769',
    'container.build_time' => 1644241430,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAzO7cQF');
