<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVatGb0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVatGb0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVatGb0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVatGb0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVatGb0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'VatGb0R',
    'container.build_id' => '9a08fb50',
    'container.build_time' => 1644775436,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVatGb0R');
