<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/850.3de69163.js',
                '/build/app.95ce4a61.js',
            ],
            'css' => [
                '/build/app.8cc41565.css',
            ],
        ],
    ],
],

]];
